{{- if .Values.huggingface.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctclip.fullname" . }}-huggingface-token
  labels:
    {{- include "ctclip.labels" . | nindent 4 }}
stringData:
  token: {{ .Values.huggingface.token }}
{{- end }}
