apiVersion: v1
kind: Service
metadata:
  name: {{ include "explorer.fullname" . }}
  labels:
    {{- include "explorer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "explorer.selectorLabels" . | nindent 4 }}
{{ if eq .Values.service.type "LoadBalancer" -}}
  {{- if gt (len .Values.service.loadBalancerSourceRanges) 0 }}
  loadBalancerSourceRanges:
    {{- range $_, $sourceRange := .Values.service.loadBalancerSourceRanges }}
    - {{ $sourceRange }}
    {{ end -}}
  {{- end -}}
{{- end }}
