EMBEDDINGS_TASK_QUEUE = "ct-clip-embeddings-activity"
WORKFLOW_TASK_QUEUE = "ct-clip-embeddings-workflow"
TEMPORAL_URI_ENV = "TEMPORAL_FRONTEND_SERVICE"
MODEL_APP_URI_ENV = "MODEL_APP_URI"
MODEL_START_TIMEOUT_SECONDS_ENV = "MODEL_START_TIMEOUT_SECONDS"
DEFAULT_MODEL_START_TIMEOUT_SECONDS = 600
DEFAULT_BATCH_SIZE = 1000
