name: Build and deploy docker image

on:
  push:

env:
  REGISTRY: ghcr.io

jobs:
  build-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ ENV.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build/Push Image - Explorer"
        uses: ./.github/actions/docker-build-push-action
        with:
          subproject: explorer
          image-name: explorer-built
