name: Example workflow

on:
  push:

jobs:
  k8s-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Start a local k8s cluster
        uses: jupyterhub/action-k3s-helm@v4
        with:
          k3s-channel: latest

      - uses: actions/checkout@v4.2.1

      - name: Verify function of k8s, kubectl, and helm
        run: |
          echo "kubeconfig: $KUBECONFIG"
          kubectl version
          kubectl get pods --all-namespaces

          helm version
          helm list

      - name: Deploy application for test
        run: |
          kubectl create namespace explorer
          kubectl create namespace ctclip
          kubectl -n explorer create secret generic ai-keys \
          --from-literal=google='your key' \
          --from-literal=azure='your key' \
          --from-literal=azure-resource='resource' \
          --from-literal=azure-assistant='assistant id' \
          --from-literal=azure-assistant-mini='assistant id'
          cd helm/ctclip
          helm upgrade --install -n ctclip ctclip . \
          --set huggingface.token=<your token> \
          --set resources.requests.memory=24000Mi \
          --set resources.requests.cpu=2
          cd -
          cd helm/explorer
          helm upgrade --install -n explorer explorer . \
          --set resources.requests.memory=4000Mi \
          --set resources.requests.cpu=2
          
