name: Post-Commit Tasks

on:
  push:

env:
  JAVA_DIST: 'zulu'
  JAVA_VERSION: '21'
  REGISTRY: ghcr.io

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12'
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ ENV.JAVA_DIST }}
          java-version: ${{ ENV.JAVA_VERSION }}
      - uses: pre-commit/action@v3.0.1

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        executorId: [ 0, 1 ]
    steps:
      - name: Start a local k8s cluster
        uses: jupyterhub/action-k3s-helm@v4
        with:
          k3s-channel: latest
          traefik-enabled: false
          
      - uses: actions/checkout@v4.2.1

      - name: Create k8s namespaces
        run: |
          kubectl create namespace explorer
          kubectl create namespace ctclip

      - name: Create storage class
        run: |
          cat>storageclass.yaml << EOF
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: weaviate
          provisioner: rancher.io/local-path
          reclaimPolicy: Delete
          volumeBindingMode: WaitForFirstConsumer
          EOF
          kubectl apply -f storageclass.yaml 
          rm storageclass.yaml

      - name: Set up secrets
        run: |
          kubectl -n explorer create secret generic ai-keys \
          --from-literal=google='your key' \
          --from-literal=azure='your key' \
          --from-literal=azure-resource='resource' \
          --from-literal=azure-assistant='assistant id' \
          --from-literal=azure-assistant-mini='assistant id'

      - name: Deploy CTCLIP
        run: |
          cd helm/ctclip
          #helm upgrade --install -n ctclip ctclip . \
          #--set huggingface.token=TODO \
          #--set resources.requests.memory=24000Mi \
          #--set resources.requests.cpu=2
          cd -

      - name: Deploy explorer
        run: |
          cd helm/explorer
          helm repo add weaviate https://weaviate.github.io/weaviate-helm
          helm dependency build
          helm upgrade --install -n explorer explorer . \
          --set resources.requests.memory=4000Mi \
          --set resources.requests.cpu=2
          cd -

      - name: kubectl describe nodes
        run: kubectl describe nodes

      - name: kubectl get nodes
        run: kubectl get nodes

      - name: kubectl -n explorer get events
        run: kubectl -n explorer get events --sort-by='.lastTimestamp'

      - name: kubectl -n explorer get all
        run: kubectl -n explorer get all

      - name: Wait for weaviate startup
        run: |
          kubectl -n explorer wait --for=condition=Ready --timeout=60s pod/weaviate-0
          kubectl -n explorer wait --for=jsonpath='{.status.loadBalancer.ingress}' --timeout=60s service/weaviate || echo "fail through"

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12'

      - name: Seed weaviate db
        run: |
          cd tests
          pip install -r requirements.txt
          python seed.py

      - uses: actions/setup-java@v4 # required by tests below, saving time by installing while app starts
        with:
          distribution: ${{ ENV.JAVA_DIST }}
          java-version: ${{ ENV.JAVA_VERSION }}

      - name: Wait for app startup
        run: |
          kubectl -n explorer wait --for=condition=available --timeout=120s deployment/explorer
          kubectl -n explorer wait --for=jsonpath='{.status.loadBalancer.ingress}' --timeout=120s service/explorer || echo "fail through"
          kubectl -n explorer get events --sort-by='.lastTimestamp'
          kubectl -n explorer describe service explorer
          kubectl -n explorer describe service weaviate

      - name: kubectl -n explorer logs service/explorer
        run: kubectl -n explorer logs service/explorer

      - name: kubectl -n explorer get all
        run: kubectl -n explorer get all

      - name: Hit the app
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://localhost --fail-with-body

      - name: Run tests
        run: |
          cd tests
          ./gradlew test -DtotalNodes=${{ strategy.job-total }} -DexecutorId=${{ matrix.executorId }}

      - name: Upload test binary
        uses: actions/upload-artifact@v4.4.3
        with:
          name: test_binary_${{ matrix.executorId }}.bin
          path: tests/build/test-results/test/binary/results.bin

      - name: Upload test log
        uses: actions/upload-artifact@v4.4.3
        with:
          name: test_executions_${{ matrix.executorId }}.json
          path: tests/build/test-results/test/test_executions_${{ matrix.executorId }}.json

  aggregate-tests:
    runs-on: ubuntu-latest
    needs: [run-tests]
    if: always()
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4.2.1

      - name: 'Download test artifacts'
        uses: actions/download-artifact@v4.1.8
        with:
          pattern: test_binary_*
          path: tests/test_result_binaries

      - name: 'Download test logs'
        uses: actions/download-artifact@v4.1.8
        with:
          pattern: test_executions_*
          path: tests/test_results

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ ENV.JAVA_DIST }}
          java-version: ${{ ENV.JAVA_VERSION }}

      - name: Aggregate tests
        run: |
          cd tests
          ./gradlew aggregateTests aggregateLogs
          zip -r aggregate_test_results.zip build/reports

      - name: Upload aggregated tests
        uses: actions/upload-artifact@v4.4.3
        with:
          name: aggregate_test_results.zip
          path: tests/aggregate_test_results.zip

  build-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs: [run-tests]
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4.2.1

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ ENV.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build/Push Image - Explorer"
        uses: ./.github/actions/docker-build-push-action
        with:
          subproject: explorer
          image-name: explorer-built
